"""Exercise HTTPS/TCP/UDP low listeners against the isolated lifecycle fixture."""
import http.client
import http.server
import json
import os
import pathlib
import socket
import ssl
import subprocess
import tempfile
import threading


class UnixClient(http.client.HTTPConnection):
    def connect(self):
        self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.sock.connect(os.environ['TRIM_APPDEST'] + '/app.sock')


def post(path, data):
    client = UnixClient('localhost', timeout=10)
    client.request('POST', '/api/' + path, json.dumps(data), {
        'Content-Type': 'application/json', 'X-FnProxy-Request': '1', 'X-Trim-Isadmin': 'true'})
    response = client.getresponse()
    body = response.read()
    assert response.status < 300, (response.status, body)
    client.close()
    return json.loads(body)


class Upstream(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'LOW_PORT_OK')

    def log_message(self, *args):
        pass


server = http.server.ThreadingHTTPServer(('127.0.0.1', 0), Upstream)
threading.Thread(target=server.serve_forever, daemon=True).start()
udp = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
udp.bind(('127.0.0.1', 0))


def echo():
    while True:
        data, address = udp.recvfrom(1024)
        udp.sendto(data, address)


threading.Thread(target=echo, daemon=True).start()
with tempfile.TemporaryDirectory() as temp:
    cert, key = pathlib.Path(temp) / 'cert.pem', pathlib.Path(temp) / 'key.pem'
    subprocess.run(['openssl', 'req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-days', '1',
                    '-subj', '/CN=lowport.test', '-keyout', str(key), '-out', str(cert)],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    certificate_pem = cert.read_text()
    cert_id = post('certificates', {'name': 'Low port test', 'certificate': cert.read_text(), 'private_key': key.read_text()})['id']
post('rules', {'name': 'Low port HTTPS', 'enabled': True, 'listen_port': 443,
               'domains': ['lowport.test'], 'tls': True, 'certificate_id': cert_id,
               'upstream_scheme': 'http', 'upstream_host': '127.0.0.1', 'upstream_port': server.server_port})
for protocol, port, upstream in [('tcp', 81, server.server_port), ('udp', 53, udp.getsockname()[1])]:
    post('streams', {'name': 'Low port ' + protocol, 'enabled': True, 'protocol': protocol,
                     'listen_address': '127.0.0.1', 'listen_port': port,
                     'upstream_host': '127.0.0.1', 'upstream_port': upstream, 'udp_responses': 1})
post('apply', {'summary': 'Low port HTTPS/TCP/UDP test'})
context = ssl.create_default_context()
# Only trust the certificate generated by this disposable fixture.
context.load_verify_locations(cadata=certificate_pem)
with socket.create_connection(('127.0.0.1', 443), timeout=5) as connection:
    with context.wrap_socket(connection, server_hostname='lowport.test') as secure:
        secure.sendall(b'GET / HTTP/1.0\r\nHost: lowport.test\r\n\r\n')
        response = b''
        while chunk := secure.recv(4096):
            response += chunk
        assert b'LOW_PORT_OK' in response, response
client = http.client.HTTPConnection('127.0.0.1', 81, timeout=5)
client.request('GET', '/')
assert client.getresponse().read() == b'LOW_PORT_OK'
client.close()
with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as client:
    client.settimeout(5)
    client.sendto(b'LOW_PORT_UDP', ('127.0.0.1', 53))
    assert client.recv(1024) == b'LOW_PORT_UDP'
server.shutdown()
udp.close()
print('HTTPS 443, TCP 81 and UDP 53 proxy checks passed')
