// Code generated by scripts/generate-dns-catalog.py; DO NOT EDIT.
package acme

import (
	"fmt"
	"github.com/go-acme/lego/v5/challenge"
	"github.com/go-acme/lego/v5/providers/dns/alidns"
	"github.com/go-acme/lego/v5/providers/dns/aliesa"
	"github.com/go-acme/lego/v5/providers/dns/azuredns"
	"github.com/go-acme/lego/v5/providers/dns/baiducloud"
	"github.com/go-acme/lego/v5/providers/dns/cloudflare"
	"github.com/go-acme/lego/v5/providers/dns/com35"
	"github.com/go-acme/lego/v5/providers/dns/desec"
	"github.com/go-acme/lego/v5/providers/dns/digitalocean"
	"github.com/go-acme/lego/v5/providers/dns/dns51"
	"github.com/go-acme/lego/v5/providers/dns/dnsla"
	"github.com/go-acme/lego/v5/providers/dns/duckdns"
	"github.com/go-acme/lego/v5/providers/dns/dynadot"
	"github.com/go-acme/lego/v5/providers/dns/edgeone"
	"github.com/go-acme/lego/v5/providers/dns/freemyip"
	"github.com/go-acme/lego/v5/providers/dns/gandiv5"
	"github.com/go-acme/lego/v5/providers/dns/gcloud"
	"github.com/go-acme/lego/v5/providers/dns/godaddy"
	"github.com/go-acme/lego/v5/providers/dns/hetzner"
	"github.com/go-acme/lego/v5/providers/dns/huaweicloud"
	"github.com/go-acme/lego/v5/providers/dns/jdcloud"
	"github.com/go-acme/lego/v5/providers/dns/linode"
	"github.com/go-acme/lego/v5/providers/dns/namecheap"
	"github.com/go-acme/lego/v5/providers/dns/namedotcom"
	"github.com/go-acme/lego/v5/providers/dns/namesilo"
	"github.com/go-acme/lego/v5/providers/dns/netlify"
	"github.com/go-acme/lego/v5/providers/dns/oraclecloud"
	"github.com/go-acme/lego/v5/providers/dns/ovh"
	"github.com/go-acme/lego/v5/providers/dns/porkbun"
	"github.com/go-acme/lego/v5/providers/dns/rainyun"
	"github.com/go-acme/lego/v5/providers/dns/route53"
	"github.com/go-acme/lego/v5/providers/dns/spaceship"
	"github.com/go-acme/lego/v5/providers/dns/tencentcloud"
	"github.com/go-acme/lego/v5/providers/dns/todaynic"
	"github.com/go-acme/lego/v5/providers/dns/ucloud"
	"github.com/go-acme/lego/v5/providers/dns/vercel"
	"github.com/go-acme/lego/v5/providers/dns/volcengine"
	"github.com/go-acme/lego/v5/providers/dns/vultr"
	"github.com/go-acme/lego/v5/providers/dns/westcn"
	"github.com/go-acme/lego/v5/providers/dns/xinnet"
)

func newNativeDNSProvider(code string) (challenge.Provider, error) {
	switch code {
	case "alidns":
		return alidns.NewDNSProvider()
	case "aliesa":
		return aliesa.NewDNSProvider()
	case "azuredns":
		return azuredns.NewDNSProvider()
	case "baiducloud":
		return baiducloud.NewDNSProvider()
	case "cloudflare":
		return cloudflare.NewDNSProvider()
	case "com35":
		return com35.NewDNSProvider()
	case "desec":
		return desec.NewDNSProvider()
	case "digitalocean":
		return digitalocean.NewDNSProvider()
	case "dns51":
		return dns51.NewDNSProvider()
	case "dnsla":
		return dnsla.NewDNSProvider()
	case "duckdns":
		return duckdns.NewDNSProvider()
	case "dynadot":
		return dynadot.NewDNSProvider()
	case "edgeone":
		return edgeone.NewDNSProvider()
	case "freemyip":
		return freemyip.NewDNSProvider()
	case "gandiv5":
		return gandiv5.NewDNSProvider()
	case "gcloud":
		return gcloud.NewDNSProvider()
	case "godaddy":
		return godaddy.NewDNSProvider()
	case "hetzner":
		return hetzner.NewDNSProvider()
	case "huaweicloud":
		return huaweicloud.NewDNSProvider()
	case "jdcloud":
		return jdcloud.NewDNSProvider()
	case "linode":
		return linode.NewDNSProvider()
	case "namecheap":
		return namecheap.NewDNSProvider()
	case "namedotcom":
		return namedotcom.NewDNSProvider()
	case "namesilo":
		return namesilo.NewDNSProvider()
	case "netlify":
		return netlify.NewDNSProvider()
	case "oraclecloud":
		return oraclecloud.NewDNSProvider()
	case "ovh":
		return ovh.NewDNSProvider()
	case "porkbun":
		return porkbun.NewDNSProvider()
	case "rainyun":
		return rainyun.NewDNSProvider()
	case "route53":
		return route53.NewDNSProvider()
	case "spaceship":
		return spaceship.NewDNSProvider()
	case "tencentcloud":
		return tencentcloud.NewDNSProvider()
	case "todaynic":
		return todaynic.NewDNSProvider()
	case "ucloud":
		return ucloud.NewDNSProvider()
	case "vercel":
		return vercel.NewDNSProvider()
	case "volcengine":
		return volcengine.NewDNSProvider()
	case "vultr":
		return vultr.NewDNSProvider()
	case "westcn":
		return westcn.NewDNSProvider()
	case "xinnet":
		return xinnet.NewDNSProvider()
	default:
		return nil, fmt.Errorf("unsupported DNS provider")
	}
}
