#!/usr/bin/env python3
"""Regenerate the native DNS catalog from the pinned lego module (Python 3.11+)."""
import json, pathlib, re, subprocess, tomllib
root = pathlib.Path(__file__).resolve().parents[1]
module = json.loads(subprocess.check_output(['go', 'list', '-m', '-json', 'github.com/go-acme/lego/v5'], cwd=root))
base = pathlib.Path(module['Dir']) / 'providers/dns'
registry = (base / 'zz_gen_dns_providers.go').read_text()
# Product scope: domestic providers plus commonly used international providers.
domestic = set("alidns aliesa tencentcloud huaweicloud baiducloud jdcloud volcengine westcn dnsla edgeone com35 dns51 rainyun todaynic ucloud xinnet".split())
international = set("cloudflare route53 azuredns gcloud oraclecloud digitalocean godaddy namedotcom namesilo namecheap porkbun spaceship dynadot desec duckdns freemyip vercel netlify ovh vultr linode hetzner gandiv5".split())
codes = domestic | international
native = set(re.findall(r'case "([^\"]+)"', registry))
if codes - native:
    raise SystemExit(f'Not native in pinned lego: {codes - native}')
packages = {}
names = {'alidns':'阿里云 DNS', 'tencentcloud':'腾讯云 DNSPod', 'huaweicloud':'华为云', 'aliesa':'阿里云 ESA', 'baiducloud':'百度云', 'jdcloud':'京东云', 'volcengine':'火山引擎', 'westcn':'西部数码', 'edgeone':'腾讯云 EdgeOne', 'dnsla':'DNS.LA', 'com35':'三五互联', 'dns51':'51DNS', 'rainyun':'雨云', 'todaynic':'时代互联', 'xinnet':'新网'}
providers = []
for path in sorted(base.glob('*/*.toml')):
    data = tomllib.loads(path.read_text())
    code = data['Code']
    if code not in codes:
        continue
    packages[code] = path.parent.name
    config = data.get('Configuration', {})
    fields = []
    for group in ['Credentials', 'Additional']:
        for key, description in config.get(group, {}).items():
            fields.append({'key':key, 'description':description, 'advanced':group=='Additional', 'secret':bool(re.search(r'TOKEN|SECRET|PASSWORD|PRIVATE|API_KEY|ACCESS_KEY|TSIG', key)), 'multiline':bool(re.search(r'JSON|PRIVATE_KEY|CERTIFICATE', key)) and not key.endswith(('_FILE', '_PATH'))})
    for key in config.get('Credentials', {}):
        if not key.endswith('_FILE') and not any(f['key'] == key+'_FILE' for f in fields):
            fields.append({'key':key+'_FILE', 'description':f'从服务器文件读取 {key}，与直接填写二选一；文件需允许应用读取。', 'advanced':True, 'secret':False, 'multiline':False})
    providers.append({'code':code,'name':names.get(code,data['Name']),'group':'国内' if code in domestic else '国际','description':data.get('Description','').strip(),'url':f'https://go-acme.github.io/lego/dns/{code}/','fields':fields})
missing = codes - {p['code'] for p in providers}
if missing:
    raise SystemExit(f'Missing provider metadata: {missing}')
providers.sort(key=lambda p: (p['code'] not in ['cloudflare','alidns','tencentcloud'], p['code'] not in domestic, p['code']))
out = {'version':module['Version'], 'providers':providers}
(root / 'internal/acme/dns_catalog.json').write_text(json.dumps(out, ensure_ascii=False, indent=2)+'\n')
print(f'{len(providers)} native DNS providers')

factory = '// Code generated by scripts/generate-dns-catalog.py; DO NOT EDIT.\npackage acme\n\nimport (\n "fmt"\n "github.com/go-acme/lego/v5/challenge"\n'
for code in sorted(codes):
    factory += f' "github.com/go-acme/lego/v5/providers/dns/{packages[code]}"\n'
factory += ')\nfunc newNativeDNSProvider(code string) (challenge.Provider, error) {\n switch code {\n'
for code in sorted(codes):
    factory += f' case "{code}": return {packages[code]}.NewDNSProvider()\n'
factory += ' default: return nil, fmt.Errorf("unsupported DNS provider")\n }\n}\n'
factory_path = root / 'internal/acme/dns_factory_generated.go'
factory_path.write_text(factory)
subprocess.run(['gofmt','-w',str(factory_path)],check=True)
